# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nick Bottomley
tagline:          "Full-stack Software Engineer"
description:      ''
url:              "http://localhost:4000"
paginate:         5
paginate_path:    "blog/page:num"

baseurl:          ""

author:
  name:           "Nick Bottomley"
  url:            "http://nickbottomley.com"

github_repo:      "https://github.com/nickb1080/personal-site"

networks:
  github:           "https://github.com/nickb1080/"
  twitter:          "https://twitter.com/bttmly"
  linkedin:         ""
  facebook:         ""
  codepen:          ""
