# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nick Bottomley
tagline:          "Web Developer"
# description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              "http://nickbottomley.com"
paginate:         5
paginate_path:    "blog/page:num"

baseurl:          "http://nickbottomley.com"

author:
  name:           "Nick Bottomley"
  url:            "http://nickbottomley.com"

github_repo:      "https://github.com/nickb1080/personal-site"

networks:
  github:           "https://github.com/nickb1080/"
  twitter:          "https://twitter.com/bttmly"
  linkedin:         ""
  facebook:         ""
  codepen:          ""

# Custom vars
# version:          1.0.0

# github:
#   repo:           https://github.com/poole/lanyon
