#!/usr/local/bin/node

var fs = require("fs");

var args = process.argv.slice(2);
var data = fs.readFileSync( "_drafts/" + args[0] );
var name = args[0];

var date = new Date();

var month = date.getMonth() + 1;
if ( month.toString().length === 1 ) {
  month = "0" + month;
}

var day = date.getDate();
if ( day.toString().length === 1 ) {
  day = "0" + day;
}

var year = date.getYear() + 1900;

var name = year + "-" + month + "-" + day + "-" + name;

fs.writeFileSync("_posts/" + name, data);